Repository PrincessGirls/22-F-Cow-PrincessDiary, pull requests merged in 2022-11, with the labels that each got.

#2 Init
  .babelrc
  .gitignore
  README.md
  app.js
  package.json
Labels: ✅완료

#4 Feat : delete 구현
  app.js
  diary.json
  gahyun/diarydelete.js
Labels: 👨🏻‍💻작업중, 가현

#6 Feat : create 구현
  content.json
  sebin/diarypost.js
Labels: 👨🏻‍💻작업중, 세빈

#5 Feat : read 구현
  dummy.json
  hyunjin/app.js
Labels: 👨🏻‍💻작업중, 현진

#7 feat : 라우팅 추가 feat: 메인페이지 구현 및 mui 등 라이브러리추가
  princess-diary_fe/package.json
  princess-diary_fe/public/images/Vector.png
  princess-diary_fe/public/images/folder.png
  princess-diary_fe/public/images/pencil.png
  princess-diary_fe/src/App.js
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#8 feat: 초기설정 및 비밀번호 입력 modal 구현
  .vscode/launch.json
  princess-diary_fe/.gitignore
  princess-diary_fe/README.md
  princess-diary_fe/package.json
  princess-diary_fe/public/favicon.ico
  princess-diary_fe/public/index.html
  princess-diary_fe/public/logo192.png
  princess-diary_fe/public/logo512.png
  princess-diary_fe/public/manifest.json
  princess-diary_fe/public/robots.txt
  princess-diary_fe/src/App.css
  princess-diary_fe/src/App.js
  princess-diary_fe/src/App.test.js
  princess-diary_fe/src/Modal_hyunjin/PasswordModal.jsx
  princess-diary_fe/src/index.css
  princess-diary_fe/src/index.js
  princess-diary_fe/src/logo.svg
  princess-diary_fe/src/reportWebVitals.js
  princess-diary_fe/src/setupTests.js
Labels: 👨🏻‍💻작업중, 현진

#10 Feat : Mainpage 추가
  princess-diary_fe/src/App.js
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
  princess-diary_fe/src/components/Princessdiary.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#11 Feat : WritePage 추가, 라우팅 전체 추가 및 수정
  package.json
  princess-diary_fe/package.json
  princess-diary_fe/src/App.js
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
  princess-diary_fe/src/Modal_hyunjin/PasswordModal.jsx
  princess-diary_fe/src/index.js
  princess-diary_fe/src/logo.svg
  princess-diary_fe/src/writepage_sebin/writepage.css
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 세빈

#12 Fix : 라우팅 전체 수정
  princess-diary_fe/package.json
  princess-diary_fe/src/App.js
  princess-diary_fe/src/index.js
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: ✅완료, 👀리뷰, 가현

#13 Feat: write 페이지 이동
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#14 Feat : WritePage 글쓰기 설정, name 속성 수정
  princess-diary_fe/package.json
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 세빈

#15 Feat : logo 추가
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: ✅완료, 👀리뷰, 세빈

#16 Feat: 다이어리 보기 화면 맛보기 구현
  princess-diary_fe/src/App.js
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.css
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.jsx
Labels: 👨🏻‍💻작업중, 현진

#17 fix: 모달창, 다이어리 컴포넌트 수정
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
  princess-diary_fe/src/Modal_hyunjin/PasswordModal.jsx
  princess-diary_fe/src/components/Princessdiary.jsx
Labels: ✅완료, 👀리뷰, 가현

#18 Feat: axios , 다이어리 화면 보여지기
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#19 Fix : button 에러 수정
  princess-diary_fe/src/writepage_sebin/writepage.css
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: 🐞버그, ✅완료, 세빈

#20 feat:좋아요 기능 구현,axios install,modal
  package.json
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.css
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.jsx
  princess-diary_fe/src/Modal_hyunjin/PasswordModal.jsx
Labels: ✅완료, 👨🏻‍💻작업중, 현진

#21 Fix: 메인 페이지 수정
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: 👨🏻‍💻작업중, 👀리뷰, 가현

#22 style: 메인페이지 폰트 관련 변경
  .vscode/settings.json
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: ✅완료, 현진

#23 feat: 해당 다이어리 view 페이지로 이동
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: ✅완료, 👀리뷰, 가현

#24 feat: 사용자에 맞는 다이어리 보여주기
  princess-diary_fe/package.json
  princess-diary_fe/src/App.js
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.jsx
  princess-diary_fe/src/MainPage_gahyun/MainPage.jsx
Labels: ✅완료, 👀리뷰, 가현

#25 Fix : post 오류 수정
  princess-diary_fe/src/writepage_sebin/writepage.css
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: 🐞버그, ✅완료, 세빈

#26 feat:뒤로가기버튼추가
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.jsx
Labels: ✅완료, 현진

#27 fix : writepage 버그 수정
  princess-diary_fe/src/App.js
  princess-diary_fe/src/writepage_sebin/writepage.jsx
Labels: 🐞버그, ✅완료, 가현

#29 Feat : Delete 구현
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.jsx
Labels: ✅완료, 세빈

#30 Feat : back Delete 기능 구현
  app.js
Labels: ✅완료, 세빈

#31 fix: writepage 경로 수정
  princess-diary_fe/src/App.js
Labels: ✅완료, 현진

#32 fix: 수정기능
  princess-diary_fe/src/DiaryViewPage_hyunjin/DiaryView.jsx
Labels: ✅완료, 👀리뷰, 가현
